### ISSUE TITLE
Web Editor - Context issue

### ISSUE THREAD

**Issue by Stardark99** [LuckPerms/LuckPermsWeb#366]
In the web editor, if you try to edit the context, the previous context is always replaced even if the option is disabled.
This occur only with a same field, for example:
i have 2 pex in context server:vanilla, if i select them and try to add a server:kitpvp, the output will be always only kitpvp and not both, but if i try to add a new parameter, like world ecc, it respects the "replace" button
![image](https://user-images.githubusercontent.com/63285633/126210519-5839fbcb-cdab-472d-8184-c0ecece4a6d0.png)
![image](https://user-images.githubusercontent.com/63285633/126210534-15ac3f87-bb6c-44a5-8a64-7d98e0c3ea80.png)
![image](https://user-images.githubusercontent.com/63285633/126210549-9d9e2bb9-4524-42b7-8c0d-1a42dfbd9b85.png)
![image](https://user-images.githubusercontent.com/63285633/126210575-41fea874-9511-40ec-bde1-acb2b4ebde81.png)

**Comment by Laarryy** [comment]
This seems to replace contexts when they have the same key. Other contexts, in my testing, are not wiped, even if a permission has a dozen contexts and you're adding a dozen, the only ones that replace are the ones that have keys which are already there. If the other ones are wiped on your end please let me know, but as it was, having several `server` contexts made the permission check guaranteed to resulted in a false permission, because you couldn't be on several servers at once. 

That behaviour has changed. It is now a bug when this happens, and should definitely be fixed - matching keys can be on the same node!
