### ISSUE TITLE
Bug in link

### ISSUE THREAD

**Issue by SnonSS** [LuckPerms/LuckPermsWeb#403]
I wrote lp editor, went to the link, everything is fine, and decided to give a link to a friend, and he went under this link and could edit privileges and players, but he couldn’t save, he didn’t have a console, how could he just go to my link which did I create this bug, or is this by design?

**Comment by BrainStone** [comment]
All links are public by design.
This is secure because in order to perform changes you need to be able to execute the `/lp apply` command, which needs specific permissions or needs to be run from the console, and only people that are supposed to be able to change permissions should have permission to those.

The idea is that you can quickly share a link to your whole permission setup and have someone else look it over or help you fix stuff.

**Comment by underscore11code** [comment]
A few months ago that was indeed the case, but about a month ago, websocket messaging was introduced. However, to enable it, you must explicitly allow the connection in MC, otherwise it defaults to the old method.
